### ISSUE TITLE
determine parameter ranges

### ISSUE THREAD

**Issue by petrelharp** [petrelharp/nebria#1]
Good news - we don't have very many parameters to tweak. My proposal is to adjust these:
- "carrying capacity" for density of adults per unit area (currently 20 per site = pixel = roughly 1km2)
- dispersal probability (currently 0.1)
- typical distance dispersed (currently 0.1km)
- something about weather variability

...and leave these alone:
- density of 'good patches' (currently 1/25th of pixels in areas of good habitat)
- mean fecundity (currently 15 that survive to adulthood per female but before density-dependent mortality)
- SD of how much habitat quality changes per year (currently 1/sqrt(200), so that it changes by 1 unit every 200 years, roughly)

For reference, the parameters are [here](https://github.com/petrelharp/nebria/blob/main/nebria.slim) in the SLiM script.

**Comment by seanschoville** [comment]
Well, I think for the dispersal probability, it seems reasonable.

I think the distance dispersed is likely fine as is if it is an average, but there may be an exponential tail that allows longer dispersal out to 1km or more. Maybe we could go as high as 0.25 for a slightly larger average

The carrying capacity probably should go up so that we ensure we have dispersal events, so perhaps an order of magnitude or at least up to 50.

**Comment by petrelharp** [comment]
> I think the distance dispersed is likely fine as is if it is an average, but there may be an exponential tail that allows longer dispersal out to 1km or more. Maybe we could go as high as 0.25 for a slightly larger average

Dispersal is a random number of Normally distributed hops, so the distribution does have a fairly long tail, FYI.

> The carrying capacity probably should go up so that we ensure we have dispersal events, so perhaps an order of magnitude or at least up to 50.

Let's see - I think the way it works now is that there's around 20 adults; the 10 females have each 15 offspring, of which 10% migrate, so about 15 migrants per patch per year. Are you thinking this should be higher?

**Comment by petrelharp** [comment]
Notes:
- the resolution and density of patches LOOKS GOOD!
- average number of eggs/female is 20ish

Changes:
- reduce fecundity to 5
- density should be higher: 40-400 (around 100-200)
- number migrating per generation: pick a number so that m=0.01-10 per year:
- maybe choose dispersal distance 0.2-2km
- and dispersal probability 0.01-0.5

Note that the important numbers are (a) how many disperse (fecundity times dispersal prob) and (b) how many survive in the same place (roughly 2 per female); just plain fecundity matters less (but affects how quick pops recover after bad years).

TODO:
1. run a small example and plot dispersal
2. run a short example and look at landscape-wide carrying capacities and proportion of occupied sites and how long it takes to run per year
3. run long simulations across a range of parameters

**Comment by petrelharp** [comment]
About dispersal: right now we have
```
 (pop size) * (1/2 females) * (fecundity) * (prob dispersal) = 200 * 1/2 * 5 * 0.1 = 50 dispersers per patch per year
```
and to have a good chance of finding new good habitat, dispersers must go kilometers, sometimes 5km; if they do then there's around a 1/20 chance they find a good patch. 

Ok, how far do they go? SIGMA is the mean dispersal distance; here's (left) the histogram of dispersal distances with SIGMA=1km, (center) the proportion of dispersal distances greater than 5km as a function of SIGMA, and (right) plots of example paths at SIGMA=1km
![Screenshot from 2021-09-21 06-11-50](https://user-images.githubusercontent.com/1046249/134176614-1f37367f-1a19-4dab-87bc-29bd0eda7c88.png)
This looks like at SIGMA=1km, about 2/1000 dispersers go 5km; of these, only 1/20 find a patch; times 50 per year thats 1 disperser per 200 years between patches separated by 5km. That's not very much. To have one migrant per year we'd need 1/50 dispersers to find a patch; if only 1/20 of long-distance dispersers actually find a patch then we'd need like half of dispersers to travel the typical inter-patch dispersal distance. 

This is telling me that we need to either (a) set the dispersal distance to be around 5km, or (b) somehow make it so that dispersing beetles preferentially find patches (in which case we could have a SIGMA of like 2km), or (c) make patches maybe 2x as dense. Now, recall that we have the quality of patches change with time, on a scale of hundreds of years, so that patches actually only spend like half the time being good patches. So, my proposal is to do (c): increase the density of potential patches to 1/10  of the pixels, but knowing that they'll only be good patches some proportion of the time (something we weren't taking into account when looking at the maps of where 'patches' are!). And then vary SIGMA from 0.1 to 5km, as we suggested above.

**Comment by petrelharp** [comment]
I'll give it a try and see what happens.

**Comment by petrelharp** [comment]
Done, see #4.
