### ISSUE TITLE
set up recapitation

### ISSUE THREAD

**Issue by petrelharp** [petrelharp/nebria#6]
When we do ABC using genetic data, we'll need to recapitate the SLiM simulation with @yimingweng's msprime simulation code.

**Comment by petrelharp** [comment]
This is `model2.py` in https://github.com/yimingweng/N_ingens_ABC - @yimingweng will get the parameter values.

**Comment by petrelharp** [comment]
Note we'll have to bin the samples from 20kya into three groups, geographically.

**Comment by yimingweng** [comment]
Hi Peter, 

The ranges and means of the parameters that can be predicted by ABC in the note here:
https://github.com/yimingweng/N_ingens_ABC/blob/master/note.md

**Comment by petrelharp** [comment]
This is mostly done; still TODO:

- pull "central points" from `geo_layers/central_points.txt`
- use parameters drawn from `N_ingens_ABC/posterior.txt`
