### ISSUE TITLE
update dates associated with periods

### ISSUE THREAD

**Issue by petrelharp** [petrelharp/nebria#7]
The more accurate dates are here: http://www.paleoclim.org/methods/

and we should change the "100% time points" to be the *middle* of the time interval.

**Comment by petrelharp** [comment]
... and the longest-ago raster, labeled `LGM`, is not on this list (the oldest is `HS`, Heinrich Stadial); for LGM we'll use 21Kya.

**Comment by petrelharp** [comment]
@yimingweng I notice we're not using the Younger Dryas, was that on purpose?

**Comment by yimingweng** [comment]
It's not on purpose becasue I didn't know we can use this model. Does it have data also for annual precipitation (in addition to temperature)? If so, it could be a better option.

**Comment by petrelharp** [comment]
I don't know! I just saw it in the list on that page you sent.

**Comment by yimingweng** [comment]
Oh, if you meant the data from Pleistocene: Younger Dryas Stadial (12.9-11.7 ka), We do have that, it's called "YDS_12_13"

**Comment by petrelharp** [comment]
Oh, good - but, I never got that one, or it didn't make it into this repository. Could you send it to me (or add it to the repository)?

**Comment by yimingweng** [comment]
My terrible mistake. I just realized I never run SDM for it. I will sent it to you once I get it.
